version: '2'

services:
  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_PASSWORD=root

  registry:
    image: registry:2.2.1
    ports:
      - 5000:5000
    container_name: "registry"

  clair:
    image: quay.io/coreos/clair
    volumes:
      - ./config:/config
    ports:
      - 6060:6060
      - 6061:6061
    container_name: "clair"
    command: --log-level=debug --config=/config/clair.yml
